gravitee-io/helm-charts

- gravitee/.helmignore
- gravitee/Chart.yaml
- gravitee/NOTES.txt
- gravitee/README.md
- gravitee/templates/_helpers.tpl
- gravitee/templates/api-autoscaler.yaml
- gravitee/templates/api-configmap.yaml
- gravitee/templates/api-deployment.yaml
- gravitee/templates/api-ingress.yaml
- gravitee/templates/api-service.yaml
- gravitee/templates/gateway-autoscaler.yaml
- gravitee/templates/gateway-configmap.yaml
- gravitee/templates/gateway-deployment.yaml
- gravitee/templates/gateway-ingress.yaml
- gravitee/templates/gateway-service.yaml
- gravitee/templates/ui-autoscaler.yaml
- gravitee/templates/ui-configmap.yaml
- gravitee/templates/ui-deployment.yaml
- gravitee/templates/ui-ingress.yaml
- gravitee/templates/ui-service.yaml
- gravitee/values.yaml
few comments:
* readme must be completed
* few things (e.g. smpt configuration are not configurable in the value.yml)
* tested with gravitee 1.15.0, mongodb 3.2 (version of the helm chart  2.1.4) elk 5.6 (version of the helm chart 0.4.9) 
* some part of the configuration assume usage of ingress services (we tested only with nginx, but of course it should work with other services, configuration may be different from the one in value.yml)
> base helm chart template

- gravitee/templates/api-configmap.yaml
When configuring debug for the API the logback.xml is incorrectly configured and causes an error starting the application.
> Fix incorrect indent in configmap

- gravitee/README.md
- gravitee/templates/api-ingress.yaml
- gravitee/templates/gateway-ingress.yaml
- gravitee/templates/ui-deployment.yaml
- gravitee/values.yaml
We want to use a different host for the gateway ingress together with the path `/` instead of the default `/gateway`.
I added a new property (`gateway.ingress.path`) which defaults to the current default. (`/gateway`)
> Use variable for gateway ingress path

- gravitee/README.md
- gravitee/templates/api-configmap.yaml
- gravitee/templates/api-deployment.yaml
- gravitee/templates/gateway-configmap.yaml
- gravitee/templates/gateway-deployment.yaml
- gravitee/values.yaml
I just had the need to enable debug logging for the gateway to solve a problem.
Unfortunately this was not possible with the chart but it is possible for the api deployment.
I added the necessary code to enable the debug logs for the gateway with the `gateway.debugEnabled`  flag.
> Gateway debug logging flag

- gravitee/templates/api-ingress.yaml
- gravitee/templates/gateway-ingress.yaml
With https://github.com/gravitee-io/gravitee-kubernetes/pull/9 the helm chart got messed up, because inside the `range $host` part we cannot reference the variable `ingress.path` directly.
@brasseld  sorry for the messup.
I fixed it and got it deployed this way.
> Fix broken ingress path variable

- gravitee/Chart.yaml
- gravitee/templates/ui-deployment.yaml
- gravitee/values.yaml
this pr allows to mount extra volumes to ui containers
this is particularly useful for example to load additional themes and locales
> add support for extra volume mounts in ui container

- apim/templates/api-service.yaml
- apim/templates/gateway-service.yaml
- apim/templates/ui-service.yaml
Changing service type in values.yml have no result on helm deployment, so this should fix it.
> changed hard coded service type to variable

- apim/Chart.yaml
- apim/templates/api-deployment.yaml
- apim/templates/gateway-deployment.yaml
- apim/values.yaml
Based on https://github.com/technosophos/k8s-helm/blob/master/docs/charts_tips_and_tricks.md#automatically-roll-deployments-when-configmaps-or-secrets-change
> Ensure Management API and Gateway pods restart after configuration change

- apim/templates/ui/ui-autoscaler.yaml
- apim/templates/ui/ui-deployment.yaml
Standardization of apim deployment apiversion. 
-  compatibility of apim management ui with kubernetes 1.16 
None
> :bug: standardization of apim deployment apiversion and support k8s 1.16

- apim/README.md
The parameters that correspond to enabling the Elasticsearch and Mongo DB dependencies are `elasticsearch.enabled` and `mongodb-replicaset.enabled` respectively, at least according to the `requirements.yaml`. This is not what is outlined in the documentation.
> Fix typos in docs. for dependency parameters

- apim/values.yaml
The right annotation is `nginx.ingress.kubernetes.io/configuration-snippet`
> [FIX] apim: Add nginx to configuration-snippet on ingress annotations

- apim/values.yaml
When installing using helm, mongo and elasticsearch services uses the helm name in the README, which is: `graviteeio-apim`
> [FIX] apim: Use correct service values for mongo and elasticsearch

- ae/Chart.yaml
- ae/templates/engine-deployment.yaml
- am/Chart.yaml
- am/templates/api/api-deployment.yaml
- am/templates/gateway/gateway-deployment.yaml
- am/templates/ui/ui-deployment.yaml
- apim/1.x/Chart.yaml
- apim/1.x/templates/api/api-deployment.yaml
- apim/1.x/templates/gateway/gateway-deployment.yaml
- apim/1.x/templates/ui/ui-deployment.yaml
- apim/3.x/Chart.yaml
- apim/3.x/templates/api/api-deployment.yaml
- apim/3.x/templates/gateway/gateway-deployment.yaml
- apim/3.x/templates/portal/portal-deployment.yaml
- apim/3.x/templates/ui/ui-deployment.yaml
Helm3 replaces the replica count set by the HPA repeatedly, resulting in a up- and down-scaling loop.
Because of that it is necessary to update the helm charts.
> add condition for replica setting

- am/requirements.yaml
- designer/requirements.yaml
Since November 13, 2020, the new location for the stable repository is https://charts.helm.sh/stable and the new location for the incubator repository is https://charts.helm.sh/incubator.
It was change on apim, but not in am and designer.
J.L.
> Fix requirements - Update Helm Chart Repository

- apim/3.x/templates/ui/ui-configmap.yaml
- apim/3.x/values.yaml
In relation to https://github.com/gravitee-io/issues/issues/2820. Be able to specify company name from `values.yaml`.
> [#2820] add company name to configmap template

- apim/3.x/templates/gateway/gateway-configmap.yaml
This commit changes the mongo section of the gateway configmap template.
The section is updated to use the same format as the api configmap
template. This allows for mongo parameter overloading using env vars.
> [#4922] Fix mongo env var overloading using helm

- cockpit/templates/api/api-ingress.yaml
see https://github.com/gravitee-io/gravitee-cockpit/issues/142 : 
I think what here makes sense, is that we add this annotation directly into the source code of the Helm Chart : that's about MLTS and cockpit connecting with APIM and AM, even in the source code of Cockpit, this is not an option, this is a core feature of Cockpit. @brasseld agreee ?
> Mtls socket nginx annotation on ingress

- apim/3.x/templates/api/api-configmap.yaml
- apim/3.x/templates/gateway/gateway-configmap.yaml
`.Values.mongo.auth.source` is only used if mongo uri is used. This PR allows to set the `authSource` in the resulting `gravitee.yml` with this value if mongo uri is not used.
Related to gravitee-io/issues#2820.
> [#2820] add mongo authSource field to configmaps when not using Mongo URI

- apim/3.x/templates/gateway/gateway-configmap.yaml
Previous PR concerning this problem forgot to include the `authSource` option inside the `ratelimit` section of the `gateway-configmap` template.
See https://github.com/gravitee-io/helm-charts/pull/87#issuecomment-775137087.
Related to gravitee-io/issues#2820.
> [#2820] add authSource field to ratelimit section

- cockpit/CHANGELOG.md
- cockpit/Chart.yaml
- cockpit/README.adoc
- cockpit/templates/api/api-configmap.yaml
- cockpit/values.yaml
Add the OIDC idp configuration.
I took the opportunity to extract the authentication config into `values.yaml`. Therefore we won't need to update the charts to update the configuration for `github`, `google` and `oidc`.
However, we would need to update the chart if we add a new IDP.
> feat(cockpit): add oidc configuration

- apim/3.x/templates/api/api-configmap.yaml
- apim/3.x/values.yaml
Hello,
We want to manage global algorithm encryption in values and remove the default admin user.
Breaking change : no more default admin in memory user.
If helm chart use want to keep the default admin user they must add the following entry in the values :
```yaml
extraInMemoryUsers: |
- user:
username: <admin (or another username if you want to secure your access)>
password: <your secudred password (bcrypt encoded if you let the default algo)>
roles: ORGANIZATION:ADMIN, ENVIRONMENT:ADMIN
```
K.R.
Benjamin.
> feat: remove default admin (in memory) user for more security

- am/templates/api/api-configmap.yaml
- am/templates/gateway/gateway-configmap.yaml
Currently am-gateway templates doesn't support mongodbconfiguration via ```.Values.mongo.servers```.
I have juste copy past mongodb configuration from am-management template and :
* added a if to remove password field form yaml file if it's define via environement variable.
* added the ability to define the authSource (missing mapping).
> Aligne am-management and am-gateway mongodb configuration

- apim/3.x/templates/gateway/gateway-configmap.yaml
- apim/3.x/values.yaml
ILM for Elastic Search indexes templates does not work actually because of theses typos.
> Fix typos in ES reporter lifecycle definition

- apim/3.x/templates/api/api-configmap.yaml
- apim/3.x/values.yaml
Our management public URL is not the ingress one.
We have a WAF Service in front of our ingress controller.
We change values to be able to change from default ingress value.
> fix: trouble with automatic management URL

- apim/3.x/CHANGELOG.md
- apim/3.x/Chart.yaml
chore: bump version to 3.1.31 and update changelog, adding support for ILM managed indexes
https://github.com/gravitee-io/issues/issues/6507
> chore: bump version to 3.1.31 and update changelog, adding support for ILM managed indexes

- apim/3.x/CHANGELOG.md
- apim/3.x/values.yaml
gravitee-io/issues#6624
In APIM, if an API is modified by multiple users at the same time, only the first can modify it. The following wil need to refresh the page. This mechanism is implemented by using ETag and if-match headers;
In our configuration, if-match header is overridden with an empty string. This fix tells to nginx to pass the header as usual.
⚠️ unable to test locally
> fix: nginx must pass if-match header

- apim/3.x/templates/_helpers.tpl
- apim/3.x/tests/gateway/deployment_redis_test.yaml
Since the CI process of APIM generates images with this template name: `${branch}-latest`, we would like to allow them to be used in helm.
It's like nightly for master but extended to support branches:
- master-latest
- 3.5.x-latest
- 3.10.x-latest
- ...
> feat: allow "latest" versions of APIM branches

- apim/3.x/.helmignore
- apim/3.x/CHANGELOG.md
- apim/3.x/templates/gateway/gateway-configmap.yaml
- apim/3.x/values.yaml
**Issue**
https://github.com/gravitee-io/issues/issues/6988
The new classloader system used on the gateway side wasn't activated by default in the code.
> chore: disable old classloader to use the new one by default

- am/CHANGELOG.md
- am/Chart.yaml
- am/templates/gateway/gateway-deployment.yaml
- am/values.yaml
> fix: allow to configure readinessProbe using administration endpoint

- apim/3.x/templates/api/api-configmap.yaml
- apim/3.x/tests/api/configmap_test.yaml
**Issue**
https://github.com/gravitee-io/issues/issues/7023
I added `jwt` attributes in APIM Management API configmap.
Regarding the naming I followed the convention started by `cookie-domain: {{ .Values.jwt.cookie.domain }}`
> Handle jwt attributes in APIM Management API

- apim/3.x/CHANGELOG.md
**Issue**
NA
The next version will be [3.1.34](https://artifacthub.io/packages/helm/graviteeio/apim3) and not 3.1.35 so I merged the sections accordingly.
I also included the changes introduced in https://github.com/gravitee-io/helm-charts/pull/219
> Fix changelog of APIM chart

- apim/3.x/CHANGELOG.md
- apim/3.x/templates/api/api-deployment.yaml
- apim/3.x/tests/api/deployment_test.yaml
**Issue**
https://github.com/gravitee-io/issues/issues/7169
This change sets the `portal.endpoint` of the API-service to the gateway endpoint
With this change the Swagger-UI has the gateway set as the default server
> Set default endpoint to the url of the gateway

- cockpit/CHANGELOG.md
- cockpit/Chart.yaml
- cockpit/values.yaml
**Issue**
https://github.com/gravitee-io/gravitee-cockpit/issues/1541
Add default api designer model creation limit.
> feat(cockpit): add default api designer model creation limit

- cockpit/README.adoc
Fix "unterminated table block" error.
> docs: fix syntax in README.adoc

- cockpit/templates/ui/ui-deployment.yaml
- cockpit/tests/ui/ui-deployment_test.yaml
The environment variable was incorrect. Cockpit UI docker image was expecting `API_URL` to configure the management API URL in `constants.json`.
It seems we didn't notice this before because it seems the Management UI image was not using the file "generated" by confd. I was using the file embedded in the zip and this file was containing `/api` as `baseURL` 🤯 
This bug has risen when we migrated Cockpit Management UI to use our `graviteeio/nginx` base image.
> fix(cockpit): fix api url environment variable name

- apim/3.x/CHANGELOG.md
- apim/3.x/Chart.yaml
- apim/3.x/templates/api/api-deployment.yaml
- apim/3.x/templates/cockpit/cockpit-certificates.yaml
- apim/3.x/tests/cockpit/configmap_test.yaml
The Cockpit secret name was hardcoded. It prevented deploying multiple APIM releases in the same namespace
> fix(apim): add template to APIM Cockpit secret name

- apim/3.x/CHANGELOG.md
- apim/3.x/Chart.yaml
- apim/3.x/templates/api/api-configmap.yaml
- apim/3.x/templates/gateway/gateway-configmap.yaml
- apim/3.x/tests/api/configmap_mongodb_test.yaml
- apim/3.x/tests/gateway/configmap_mongodb_test.yaml
**Issue**
https://github.com/gravitee-io/issues/issues/7539
Add support for `keystore` and `truststore` in MongoDB config
> APIM: Add support for `keystore` and `truststore` in MongoDB config

- apim/3.x/CHANGELOG.md
- apim/3.x/Chart.yaml
chore(apim): move 3.1.46 changes to 3.1.45 to avoid missing version number
> chore(apim): move 3.1.46 changes to 3.1.45 to avoid missing version number

- ae/CHANGELOG.md
- ae/Chart.yaml
**Issue**
https://github.com/gravitee-io/issues/issues/8314
This PR bumps AE charts to the next version
PR merged: https://github.com/gravitee-io/helm-charts/pull/284
> chore(ae): bump chart to next version

- apim/3.x/Chart.yaml
- apim/3.x/templates/api/api-configmap.yaml
- apim/3.x/tests/api/configmap_test.yaml
**Issue**
https://github.com/gravitee-io/issues/issues/8303
authorize some special characters when fetching UI ingress path to compute management.url setting
> Authorize some special characters when fetching UI ingress path to compute management.url setting

- cockpit/CHANGELOG.md
- cockpit/Chart.yaml
- cockpit/templates/api/api-configmap.yaml
- cockpit/tests/api/api-configmap_logback_yaml_test.yaml
Use ISO 8601 timezone representation in json logging to fix filebeat parsing problems ([stackoverflow thread](https://stackoverflow.com/questions/57920043/failing-to-parse-date-in-logstash-with-format-strict-date-optional-timeepoch))
> fix(cockpit): use ISO8601 timezone in json logging

- apim/3.x/CHANGELOG.md
- apim/3.x/Chart.yaml
- apim/3.x/templates/api/api-configmap.yaml
- apim/3.x/templates/gateway/gateway-configmap.yaml
- apim/3.x/tests/api/configmap_logback_yaml_test.yaml
- apim/3.x/tests/gateway/configmap_logback_yaml_test.yaml
Use ISO 8601 timezone representation in json logging to fix filebeat parsing problems
see https://stackoverflow.com/questions/57920043/failing-to-parse-date-in-logstash-with-format-strict-date-optional-timeepoch
see https://github.com/gravitee-io/helm-charts/pull/290
> fix(apim): use ISO8601 timezone in json logging

- apim/3.x/templates/api/api-deployment.yaml
- apim/3.x/templates/gateway/gateway-deployment.yaml
**Issue**
[#8345](https://github.com/gravitee-io/issues/issues/8345)
Following the following error during a test deployment.  
helm-controller reconciliation failed: Helm upgrade failed: failed to create resource: Deployment.apps "abc-d-01--abcd-efg" is invalid: spec.template.spec.containers[0].ports[1].name: Invalid value: "abcd-efg-techapi": must be no more than 15 characters  
To solve it, I just truncate port name for bridge and technical port on api and gateway deployment templates.
We are trying to deploy 2 control plane on the same cluster and must rename the release, deployments and pods.
> fix: error port name too long

- apim/3.x/CHANGELOG.md
- apim/3.x/Chart.yaml
- apim/3.x/requirements.lock
- apim/3.x/requirements.yaml
- apim/3.x/values.yaml
It seems that using an alias breaks the condition when we depend on multiple APIM chart.
For example, if we deploy an umbrella chart like:
```
apiVersion: v2
name: jgo
description: an environment
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
- name: apim3
version: 3.1.52
repository: https://helm.gravitee.io
alias: apim
- name: apim3
version: 3.1.52
repository: https://helm.gravitee.io
alias: apim-dev
```
It will create the following:
- Source: jgo/charts/apim-dev/charts/mongodb/templates/serviceaccount.yaml
- Source: jgo/charts/apim-dev/charts/mongodb/templates/secrets.yaml
- Source: jgo/charts/apim-dev/charts/mongodb/templates/common-scripts-cm.yaml
- Source: jgo/charts/apim-dev/charts/mongodb/templates/standalone/pvc.yaml
- Source: …
> fix(apim): remove alias for mongodb chart dependency

- apim/3.x/CHANGELOG.md
- apim/3.x/Chart.yaml
- apim/3.x/tests/api/deployment_livenessProbe_test.yaml
- apim/3.x/tests/api/deployment_readinessProbe_test.yaml
- apim/3.x/tests/api/deployment_startupProbe_test.yaml
- apim/3.x/values.yaml
Depending on the time to execute java upgraders during a version upgrade, we encountered issues when k8s restarted the pod even if the upgrade was not finished.
The "workaround" is to add a startup probe to accept a long initial startup.
> Add a startup probe on m-api

- cockpit/templates/_helpers.tpl
- cockpit/templates/api/api-deployment.yaml
- cockpit/templates/generator/generator-deployment.yaml
- cockpit/templates/ui/ui-deployment.yaml
- cockpit/tests/api/api-deployment_test.yaml
- cockpit/tests/generator/generator-deployment_test.yaml
- cockpit/tests/ui/ui-deployment_test.yaml
**Issue**
https://github.com/gravitee-io/gravitee-cockpit/issues/3117
I'm using templates to merge default affinity with provided ones if defined in `values.yml`
See: https://rm3l.org/merging-dynamic-config-data-in-helm-charts/
> feat(cockpit): define default pod anti-affinity

- apim/3.x/CHANGELOG.md
- apim/3.x/Chart.yaml
- apim/3.x/templates/api/api-configmap.yaml
- apim/3.x/tests/api/configmap_email_test.yaml
- apim/3.x/values.yaml
Reapply https://github.com/gravitee-io/helm-charts/pull/299 with a breaking change to ensure the generated config-map is ok.
BREAKING CHANGE: Use `smtp.properties.starttls.enable` instead of `smtp.properties.starttlsEnable`
> APIM: Use `smtp.properties` directly instead of copying properties one by one

- apim/3.x/templates/api/api-deployment.yaml
- apim/3.x/templates/gateway/gateway-deployment.yaml
- apim/3.x/templates/portal/portal-deployment.yaml
- apim/3.x/templates/ui/ui-deployment.yaml
An error can occurs when a user tries to install apim with the 3.19 ui tag. It's considered as a number but the labels can only use strings
Current error:
> fix: quote apim ui version in deployment spec labels

- apim/3.x/templates/gateway/gateway-configmap.yaml
- apim/3.x/values.yaml
variabilize the keepalive and timeouts in the gateway's configmap template for the connection to bridge
> variabilize the keepalive and timeouts for the connection to bridge

- cockpit/CHANGELOG.md
- cockpit/Chart.yaml
- cockpit/templates/api/api-configmap.yaml
- cockpit/tests/api/api-configmap_hazelcast_yaml_test.yaml
**Issue**
https://graviteedevops.atlassian.net/browse/COC-57
With ArgoCD, the revision number will be always 1. In that case we will generate a unique cluster name using the SHA1 of the tag
> fix(cockpit): generate hazelcast cluster name using the sha of the tag

- am/README.adoc
- am/README.md
- apim/3.x/README.adoc
- apim/3.x/README.md
**Issue**
https://graviteedevops.atlassian.net/browse/DOC-293
I added a note about using secrets and namespaces to the APIM and AM `README.*` files. The `adocc` files are `include`d in pages on the docs site. The note was added to the `md` files as well to keep them in sync.
> Adding note about roles and namespaces

- apim/3.x/templates/gateway/gateway-configmap.yaml
- apim/3.x/tests/gateway/configmap_tracing_test.yaml
- apim/3.x/values.yaml
I added values to define tracing options according to https://docs.gravitee.io/apim/3.x/apim_enable_opentracing_with_jaeger.html as well as the corresponding definition inside the configmap.
> feat(apim): added option to define tracing inside of ConfigMap

- am/CHANGELOG.md
- am/Chart.yaml
- am/templates/api/api-configmap.yaml
- am/templates/gateway/gateway-configmap.yaml
- apim/3.x/CHANGELOG.md
- apim/3.x/Chart.yaml
- apim/3.x/templates/api/api-configmap.yaml
- apim/3.x/templates/gateway/gateway-configmap.yaml
Avoid null value when configuring ae without alerts.option
> fix(apim): avoid null value for ae configuration

- apim/3.x/CHANGELOG.md
- apim/3.x/Chart.yaml
- apim/3.x/templates/api/api-configmap.yaml
- apim/3.x/templates/gateway/gateway-configmap.yaml
- apim/3.x/tests/api/configmap_metrics_test.yaml
- apim/3.x/tests/gateway/configmap_metrics_test.yaml
**Issue**
https://github.com/gravitee-io/issues/issues/7927
Add `labels` in the metrics config of the Management API and Gateway
> Add `labels` in the metrics config of the Management API and Gateway

- .github/CODEOWNERS
**Issue**
https://github.com/gravitee-io/issues/issues/XXXXX
> chore: Update codeowners to define devops as admin instead of techops

- am/CHANGELOG.md
- am/Chart.yaml
- am/templates/api/api-upgrader-job.yaml
- apim/3.x/CHANGELOG.md
- apim/3.x/Chart.yaml
- apim/3.x/templates/api/api-upgrader-job.yaml
- apim/3.x/tests/api/api_upgrader_test.yaml
- cockpit/CHANGELOG.md
- cockpit/Chart.yaml
- cockpit/templates/api/api-upgrader-job.yaml
- cockpit/tests/api/api_upgrader_test.yaml
This small fix is just trying to remove the upgrader job before running any new one. This is needed to automatically remove failled jobs in the case that there was an error during the upgrade.
If there was no error during the upgrade, the job will be removed automatically.
> fix: add hook-delete-policy

- apim/3.x/README.adoc
- apim/3.x/templates/portal/portal-configmap.yaml
- apim/3.x/templates/ui/ui-configmap.yaml
- apim/3.x/values.yaml
I saw that HTTP had been requested for testing purposes here:  https://community.gravitee.io/t/helm-chart-apim3-issues/311/10 and thought I'd add this in.
**Issue**
https://github.com/gravitee-io/issues/issues/8957
-  `ui-configmap`: adjusted so BaseURL option pulls from the values file whether to use HTTP or HTTPS
- `portal-configmap`: adjusted so BaseURL option pulls from the values file whether to use HTTP or HTTPS
- `readme.adoc`: Added documentation for the UI but couldn't find where the portal section was so didn't add docs for that one
> Adding option to allow for http communication to management api

- am/CHANGELOG.md
- am/Chart.yaml
- am/templates/_helpers.tpl
- am/templates/api/api-configmap.yaml
- am/templates/api/api-deployment.yaml
- am/templates/gateway/gateway-configmap.yaml
- am/templates/gateway/gateway-deployment.yaml
- am/tests/api/external_configuration.yaml
- am/tests/gateway/external_configuration.yaml
- apim/3.x/CHANGELOG.md
- apim/3.x/Chart.yaml
- apim/3.x/templates/_helpers.tpl
- apim/3.x/templates/api/api-configmap.yaml
- apim/3.x/templates/api/api-deployment.yaml
- apim/3.x/templates/gateway/gateway-configmap.yaml
- apim/3.x/templates/gateway/gateway-deployment.yaml
- apim/3.x/tests/api/external_configuration.yaml
- apim/3.x/tests/gateway/external_configuration.yaml
- apim/3.x/values.yaml
**Issue**
Unable to use the value parameter `logging.debug: true` when using an external gravitee.yml
This pr allow user to set `logging.debug: true` when using an external gravitee.yml:
- a configMag is generated with logback.xml
- The provided gravitee.yml is used by the application
> logback.xml

- .circleci/config.yml
**Issue**
CI is KO because the vision was upgraded from 0.2.11 to 0.3.1.
> fix(unitest): fix version

- cockpit/CHANGELOG.md
- cockpit/Chart.yaml
- cockpit/templates/api/api-configmap.yaml
- cockpit/tests/api/api-configmap_gravitee_yaml_test.yaml
Add the test: 'should enable notifiers when TLS enabled without truststore' and make it pass.
> fix(cockpit): on notifiers configuration, allow TLS without custom keystore

- apim/3.x/CHANGELOG.md
- apim/3.x/Chart.yaml
- apim/3.x/templates/gateway/gateway-configmap.yaml
While introducing new cache manager, a old and used cache.type configuration has been removed and is in conflict with the new mechanism. This PR just remove it from the hard coded config map.
> fix: remove old cache type configuration

- apim/3.x/CHANGELOG.md
- apim/3.x/Chart.yaml
- apim/3.x/templates/gateway/gateway-configmap.yaml
- apim/3.x/values.yaml
labels are required by the Kubernetes Operator to access gateway configuration
> feat: add labels to apim gateway configmap

- ae/Chart.yaml
- ae/templates/engine-deployment.yaml
- ae/tests/deployment_test.yaml
- ae/values.yaml
- cockpit/Chart.yaml
- cockpit/templates/api/api-deployment.yaml
- cockpit/templates/generator/generator-deployment.yaml
- cockpit/templates/ui/ui-deployment.yaml
- cockpit/tests/api/api-deployment_test.yaml
- cockpit/tests/generator/generator-deployment_test.yaml
- cockpit/tests/ui/ui-deployment_test.yaml
- cockpit/values.yaml
**Issue**
Issue [#9209](https://github.com/gravitee-io/issues/issues/9209) on APIM replicated to Cockpit and AE.
[https://gravitee.atlassian.net/browse/DEVOPS-179](DEVOPS-179)
Add podSecurityContext at deployment spec level
In addition of the container level, you can now define a security
context at pod level.
DEVOPS-179
> feat: Add podSecurityContext at deployment spec level

- ae/Chart.yaml
- ae/templates/engine-ingress.yaml
- ae/templates/engine-technical-ingress.yaml
- ae/tests/ingress_technical_test.yaml
- ae/tests/ingress_test.yaml
- cockpit/Chart.yaml
- cockpit/templates/api/api-ingress-technical.yaml
- cockpit/templates/api/api-ingress-ws.yaml
- cockpit/templates/api/api-ingress.yaml
- cockpit/templates/ui/ui-ingress.yaml
- cockpit/tests/api/api-ingress-technical_test.yaml
- cockpit/tests/api/api-ingress-ws_test.yaml
- cockpit/tests/api/api-ingress_test.yaml
**Issue**
linked to https://gravitee.atlassian.net/browse/APIM-2736
DEVOPS-202 > DEVOPS-206 // DEVOPS-207
Allow ingress host wildcard
Allow usage of ingress wildcard.
Without quote, the use of '*' in the ingress host cause an yaml issue
> feat: allow ingress host wildcard

- ae/CHANGELOG.md
- ae/Chart.yaml
- ae/templates/licenses-secrets.yaml
- ae/values.yaml
**Issue**
https://gravitee.atlassian.net/browse/DV-332
During an helm upgrade, the secret with gravitee license created
from `values.yml` entry: `license.key` is deleted.
It seems that the lookup implies that the ressource is not re-created,
however during the helm upgrade rotation it is deleted.
The fix consist on removing this lookup and by default name the secret
with component suffix. We set this suffix to allow specific use case
with multiple gravitee component on the same namespace (eg: APIM+AE).
> fix(helm): license deleted after helm upgrade

- .circleci/config.yml
- cockpit/CHANGELOG.md
- cockpit/templates/api/api-configmap.yaml
- cockpit/templates/api/api-deployment.yaml
- cockpit/templates/api/api-service-hz.yaml
- cockpit/tests/api/api-configmap_gravitee_yaml_test.yaml
- cockpit/tests/api/api-configmap_hazelcast_yaml_test.yaml
- cockpit/tests/api/api-configmap_logback_yaml_test.yaml
- cockpit/tests/api/api-deployment_test.yaml
- cockpit/tests/api/api-ingress-technical_test.yaml
- cockpit/tests/api/api-pdb_test.yaml
- cockpit/tests/api/api_upgrader_test.yaml
- cockpit/tests/extra-manifests_test.yaml
- cockpit/tests/generator/generator-configmap_test.yaml
- cockpit/tests/generator/generator-deployment_test.yaml
- cockpit/tests/generator/generator-pdb_test.yaml
- cockpit/tests/ui/ui-configmap_test.yaml
- cockpit/tests/ui/ui-deployment_test.yaml
- cockpit/tests/ui/ui-ingress_test.yaml
- cockpit/tests/ui/ui-pdb_test.yaml
**Issue**
https://gravitee.atlassian.net/browse/ARCHI-391
This fixes issues for Cockpit when running on Kubernetes. 2 Hazelcast clusters, one for cache and one for gravitee clustering, were created on the same port and caused Hz discovery issues leading to cache inconsistencies and failures when connecting APIM or AM installations to Cockpit.
> fix: split hz config for cluster and cache

- index.yaml
all Helm Charts with amended changelogs are not visible in ArtifactHub. 
According to https://gravitee.slab.com/posts/helm-chart-release-lifecycle-h7m002pk#hdbxl-concretely-what-should-i-do ":" is forbidden character and should be enclosed in quotes.
> fix: colon is forbidden character and cannot be used in changelog
