gravitee-io/helm-charts

gravitee/templates/api-configmap.yaml, gravitee/values.yaml
Fixes https://github.com/gravitee-io/issues/issues/1600
=> Parameterized SMTP details and admin password

gravitee/templates/api-configmap.yaml, gravitee/values.yaml
To guide users to not use the default
=> Parameterized JWT Secret

gravitee/Chart.yaml, gravitee/README.md, gravitee/templates/api-configmap.yaml, gravitee/templates/api-deployment.yaml, gravitee/templates/api-ingress.yaml, gravitee/templates/gateway-configmap.yaml, gravitee/templates/gateway-ingress.yaml, gravitee/templates/ui-configmap.yaml, gravitee/templates/ui-deployment.yaml, gravitee/values.yaml
Add instructions on how to package the chart and how to install the packaged chart
Fix variables and values for ingress and deployments
Fix API, Gateway and UI settings on config maps
=> Fix chart values (with examples)

gravitee/templates/api-configmap.yaml
The related issuse is: https://github.com/gravitee-io/issues/issues/2128
=> update api-configmap.yaml to make services.http.core work

gravitee/templates/api-deployment.yaml, gravitee/templates/gateway-deployment.yaml, gravitee/templates/ui-deployment.yaml
The node selector was in "containers" it should be in "spec"
=> Node selector fix (it was not working because it was not at the good place)

gravitee/templates/api-configmap.yaml, gravitee/values.yaml
This small PR allows to define additional in memory users from the helm chart values.
=> Allow to define extra in memory users from helm chart values

gravitee/templates/ui-deployment.yaml
=> fix missing volume mount :sob:

apim/Chart.yaml, apim/README.md, apim/templates/api-configmap.yaml, apim/templates/gateway-configmap.yaml, apim/templates/ui-configmap.yaml, apim/values.yaml
Extends MongoDB configuration and fix some other options
=> Mongodb options

apim/values.yaml
Closes gravitee-io/issues#2590
=> doc: Add doc on how to add email on a user inmemory

apim/Chart.yaml, apim/templates/api-autoscaler.yaml, apim/templates/api-configmap.yaml, apim/templates/api-deployment.yaml, apim/templates/api-ingress.yaml, apim/templates/api-service.yaml, apim/templates/gateway-autoscaler.yaml, apim/templates/gateway-configmap.yaml, apim/templates/gateway-deployment.yaml, apim/templates/gateway-ingress.yaml, apim/templates/gateway-service.yaml, apim/templates/ui-autoscaler.yaml, apim/templates/ui-configmap.yaml, apim/templates/ui-deployment.yaml, apim/templates/ui-ingress.yaml, apim/templates/ui-service.yaml
See https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/
=> Apply K8S recommendations for labels

apim/templates/api/api-autoscaler.yaml, apim/templates/gateway/gateway-autoscaler.yaml
Bug fix
This PR is a proposal for the apim autoscalers :
Autoscaler targer the wrong api version : apps/v1beta1
None
=> :bug: apim autoscaler fix wrong apiversion target

apim/README.adoc, apim/README.md, apim/templates/api/api-configmap.yaml, apim/templates/gateway/gateway-configmap.yaml, apim/values.yaml
Closes gravitee-io/issues#3204
=> feat: allow the configuration of elasticsearch ssl

apim/3.x/Chart.yaml, apim/3.x/templates/api/api-deployment.yaml, apim/3.x/templates/gateway/gateway-deployment.yaml, apim/3.x/templates/portal/portal-deployment.yaml, apim/3.x/templates/ui/ui-deployment.yaml, apim/3.x/values.yaml
Closes gravitee-io/issues#4078
=> k8s: Ensure running runAsNonRoot for all Gravitee pods

apim/1.x/templates/api/api-configmap.yaml, apim/1.x/values.yaml, apim/3.x/templates/api/api-configmap.yaml, apim/3.x/values.yaml
=> fix:  Handle default values for notifiers configuration

apim/3.x/requirements.lock, apim/3.x/requirements.yaml
resolves https://github.com/gravitee-io/issues/issues/4646
=> Fix helm requirements

apim/3.x/templates/api/api-configmap.yaml, apim/3.x/values.yaml
resolves https://github.com/gravitee-io/issues/issues/4645
=> Allow the configuration of an OIDC-Provider via Helm-chart

apim/3.x/Chart.yaml, apim/3.x/templates/api/api-configmap.yaml
=> feat: add custom management console URL handling

apim/3.x/templates/_helpers.tpl
resolves https://github.com/gravitee-io/issues/issues/4868
=> Let the full name be configurable

ae/.helmignore, ae/README.adoc, ae/README.md, ae/rbac.yml, ae/templates/engine-configmap.yaml, ae/templates/engine-deployment.yaml, ae/values.yaml
Closes gravitee-io/gravitee-alert-engine#176
=> fix(kubernetes): fix ae stability issues when deployed on k8s cluster

apim/3.x/templates/api/api-configmap.yaml, apim/3.x/values.yaml
Closes gravitee-io/issues#5141
=> feat: Allows to configure trust all on IDPs

apim/3.x/templates/gateway/gateway-configmap.yaml, apim/3.x/values.yaml
Closes gravitee-io/issues#5143
=> chore: Add support for reporter configuration

apim/3.x/CHANGELOG.md, apim/3.x/Chart.yaml, apim/3.x/templates/gateway/gateway-deployment.yaml
Closes gravitee-io/issues#5283
=> apim: do not apply special treatment for nightly tag

am/CHANGELOG.md, am/Chart.yaml, am/README.adoc, am/templates/_helpers.tpl, am/templates/api/api-configmap.yaml, am/templates/api/api-deployment.yaml, am/templates/gateway/gateway-configmap.yaml, am/templates/gateway/gateway-deployment.yaml, am/templates/ui/ui-configmap.yaml, am/templates/ui/ui-deployment.yaml, am/values.yaml
=> am: update Chart missing values

am/CHANGELOG.md, am/Chart.yaml, am/templates/gateway/gateway-configmap.yaml, am/values.yaml
closes gravitee-io/issues#5355
=> feat(ssl): add tls protocols

apim/3.x/CHANGELOG.md, apim/3.x/Chart.yaml, apim/3.x/templates/gateway/gateway-configmap.yaml, apim/3.x/values.yaml
Closes gravitee-io/issues#5378
=> feat(apim): Add support for policy configuration from gravitee.yml

apim/3.x/CHANGELOG.md, apim/3.x/Chart.yaml, apim/3.x/templates/gateway/gateway-configmap.yaml
Closes gravitee-io/issues#5415
=> Enable only if the ssl dictionary is defined from values

cockpit/templates/api/api-configmap.yaml, cockpit/values.yaml
gravitee-io/gravitee-cockpit#534
=> feat: add cockpit compatible versions configuration

cockpit/templates/api/api-configmap.yaml, cockpit/values.yaml
Closes gravitee-io/gravitee-cockpit#557
=> feat: add cockpit support for email notifications configuration

cockpit/CHANGELOG.md, cockpit/Chart.yaml, cockpit/templates/api/api-configmap.yaml, cockpit/values.yaml
The goal of this pull request is to define the new attributes added in the following pull requests
https://github.com/gravitee-io/gravitee-cockpit/pull/584
https://github.com/gravitee-io/cloud-cockpit/pull/4
=> feat: define health check report cron job and initial plan attributes

cockpit/README.adoc, cockpit/rbac.yml, cockpit/templates/api/api-configmap.yaml, cockpit/templates/api/api-deployment.yaml
Related to https://github.com/gravitee-io/gravitee-cockpit/pull/599
=> feat(cockpit): add hazelcast configuration

apim/3.x/CHANGELOG.md, apim/3.x/Chart.yaml, apim/3.x/templates/api/api-configmap.yaml, apim/3.x/templates/gateway/gateway-configmap.yaml
Closes gravitee-io/issues#5662
=> fix(apim): Disable Alert Engine connector when alerting is disabled

apim/3.x/CHANGELOG.md, apim/3.x/Chart.yaml, apim/3.x/templates/api/api-configmap.yaml, apim/3.x/templates/gateway/gateway-configmap.yaml
this pull request (https://github.com/gravitee-io/helm-charts/pull/114)
does not fix the issue.
fix gravitee-io/issues#5662
=> fix AE configuration

apim/3.x/CHANGELOG.md, apim/3.x/Chart.yaml, apim/3.x/templates/api/api-configmap.yaml, apim/3.x/templates/gateway/gateway-configmap.yaml, apim/3.x/values.yaml
Closes gravitee-io/issues#5565
=> feat(apim3): Add values support for Prometheus configuration

designer/CHANGELOG.md, designer/Chart.yaml, designer/templates/api/api-ingress.yaml
Closes gravitee-io/issues#5797
=> fix(designer): Remove useless API ingress path regex capture

apim/3.x/CHANGELOG.md, apim/3.x/Chart.yaml, apim/3.x/templates/gateway/gateway-bridge-ingress.yaml
Closes gravitee-io/issues#5798
=> fix(apim): Gateway Bridge Ingress based on networking.k8s.io

apim/3.x/CHANGELOG.md, apim/3.x/Chart.yaml, apim/3.x/templates/NOTES.txt, apim/3.x/templates/api/api-deployment.yaml, apim/3.x/templates/gateway/gateway-deployment.yaml, apim/3.x/templates/portal/portal-deployment.yaml, apim/3.x/templates/ui/ui-deployment.yaml, apim/3.x/values.yaml
Closes gravitee-io/issues#5809
=> chore: Improve APIM deployment configurability

am/CHANGELOG.md, am/Chart.yaml, am/templates/NOTES.txt, am/templates/api/api-deployment.yaml, am/templates/gateway/gateway-autoscaler.yaml, am/templates/gateway/gateway-deployment.yaml, am/templates/ui/ui-deployment.yaml, am/values.yaml
Closes gravitee-io/issues#5810
=> chore: Improve AM deployment configurability

cockpit/CHANGELOG.md, cockpit/Chart.yaml, cockpit/README.adoc, cockpit/templates/_helpers.tpl, cockpit/templates/api/api-clusterrole.yaml, cockpit/templates/api/api-clusterrolebinding.yaml, cockpit/templates/api/api-deployment.yaml, cockpit/templates/api/api-serviceaccount.yaml, cockpit/values.yaml
Closes gravitee-io/gravitee-cockpit#762
=> chore: Add support for service account

am/values.yaml, cockpit/templates/NOTES.txt, cockpit/templates/api/api-deployment.yaml, cockpit/templates/ui/ui-deployment.yaml, cockpit/values.yaml
Closes gravitee-io/gravitee-cockpit#763
=> chore: chore: Improve Cockpit deployment configurability

am/CHANGELOG.md, am/Chart.yaml, am/templates/api/api-configmap.yaml, am/templates/gateway/gateway-configmap.yaml, am/templates/ui/ui-configmap.yaml, am/tests/api-configmap_test.yaml, am/tests/ui-configmap_test.yaml, am/values.yaml
=> feat: make entrypoint configurable for AM API

am/CHANGELOG.md, am/Chart.yaml, am/templates/api/api-configmap.yaml, am/tests/api-configmap_test.yaml, am/values.yaml
=> fix: update endpoint management introduce in 1.0.22

cockpit/CHANGELOG.md, cockpit/Chart.yaml, cockpit/values.yaml
https://github.com/gravitee-io/gravitee-cockpit/issues/807
=> chore(cockpit): make management-api ingress sse compatible

cockpit/CHANGELOG.md, cockpit/Chart.yaml, cockpit/templates/_helpers.tpl, cockpit/templates/generator/generator-autoscaler.yaml, cockpit/templates/generator/generator-configmap.yaml, cockpit/templates/generator/generator-deployment.yaml, cockpit/templates/generator/generator-service.yaml, cockpit/values.yaml
https://github.com/gravitee-io/gravitee-cockpit/issues/698
=> feat(cockpit): add swagger-generator deployment

apim/3.x/README.adoc
Rewrite of info to install PostgresSQL via JDBC. @marcambier, could you please take a look at this?
=> Update ReadMe Include

ae/CHANGELOG.md, ae/Chart.yaml, ae/templates/engine-configmap.yaml
Closes gravitee-io/gravitee-alert-engine#227
=> chore(ae): update hazelcast config

apim/3.x/templates/api/api-configmap.yaml, apim/3.x/templates/gateway/gateway-configmap.yaml, apim/3.x/values.yaml
https://github.com/gravitee-io/issues/issues/6507
feat: add elasticsearch index_mode configuration in api and gateway configurations, filled from values.yml
=> feat: add elasticsearch index_mode configuration in api and gateway configurations, filled from values.yml

ae/CHANGELOG.md, ae/Chart.yaml, ae/templates/engine-deployment.yaml, ae/values.yaml, am/CHANGELOG.md, am/Chart.yaml, am/templates/api/api-deployment.yaml, am/templates/gateway/gateway-deployment.yaml, am/templates/ui/ui-deployment.yaml, am/values.yaml, apim/3.x/CHANGELOG.md, apim/3.x/Chart.yaml, apim/3.x/templates/api/api-deployment.yaml, apim/3.x/templates/gateway/gateway-deployment.yaml, apim/3.x/templates/ui/ui-deployment.yaml, apim/3.x/tests/gateway/deployment_additional-plugins_test.yaml, apim/3.x/tests/gateway/deployment_jdbc_test.yaml, apim/3.x/tests/gateway/deployment_redis_test.yaml, apim/3.x/tests/gateway/deployment_test.yaml, apim/3.x/values.yaml, cockpit/CHANGELOG.md, cockpit/Chart.yaml, cockpit/templates/api/api-deployment.yaml, cockpit/templates/ui/ui-deployment.yaml
Closes gravitee-io/issues#6717
=> Platform: Add support for revisionHistoryLimit

apim/3.x/CHANGELOG.md, apim/3.x/Chart.yaml, apim/3.x/README.md, apim/3.x/templates/gateway/gateway-configmap.yaml, apim/3.x/tests/gateway/configmap_es_reporter_ingest_plugins_test.yaml, apim/3.x/values.yaml
https://github.com/gravitee-io/issues/issues/6683
Add elasticSearch reporter ingest plugins configuration
=> feat: add elasticSearch reporter ingest plugins configuration

am/templates/gateway/gateway-configmap.yaml, am/values.yaml
Proposal to add support for AM Gateway's HTTP parameters that are normally available in gravitee.yml
=> fix(am): Added missing AM Gateway HTTP params

cockpit/templates/_helpers.tpl, cockpit/templates/api/api-deployment.yaml, cockpit/templates/common/cockpit-clusterrole.yaml, cockpit/templates/common/cockpit-clusterrolebinding.yaml, cockpit/templates/common/cockpit-serviceaccount.yaml, cockpit/templates/generator/generator-deployment.yaml, cockpit/templates/ui/ui-deployment.yaml, cockpit/values.yaml
Rename `cookpit` into `cockpit`
=> fix(cockpit): typo in service account resources

cockpit/CHANGELOG.md, cockpit/Chart.yaml, cockpit/values.yaml
Use the correct image name for the Swagger Generator to prevent overriding it
=> Fix swagger generator image

cockpit/CHANGELOG.md, cockpit/Chart.yaml, cockpit/templates/api/api-configmap.yaml, cockpit/templates/api/api-deployment.yaml, cockpit/values.yaml
Add a value to define additional loggers in logback configuration
=> feat(cockpit): define additional loggers in logback configuration

.circleci/config.yml, am/TESTS.md, apim/3.x/TESTS.md, apim/3.x/tests/gateway/deployment_jdbc_test.yaml, apim/3.x/tests/gateway/deployment_redis_test.yaml
Add a simple CI workflow with: 
- helm lint for AE, Cockpit and Designer
- helm lint + unittest for APIM and AM
=> Run lint and unit tests in CI

.circleci/config.yml, cockpit/.helmignore, cockpit/templates/api/api-configmap.yaml, cockpit/templates/common/cockpit-clusterrole.yaml, cockpit/templates/common/cockpit-clusterrolebinding.yaml, cockpit/templates/common/cockpit-serviceaccount.yaml, cockpit/tests/api/api-autoscaler_test.yaml, cockpit/tests/api/api-configmap_gravitee_yaml_test.yaml, cockpit/tests/api/api-configmap_hazelcast_yaml_test.yaml, cockpit/tests/api/api-deployment_test.yaml, cockpit/tests/api/api-ingress-technical_test.yaml, cockpit/tests/api/api-ingress-ws_test.yaml, cockpit/tests/api/api-ingress_test.yaml, cockpit/tests/api/api-service_test.yaml, cockpit/tests/common/cockpit-clusterrole_test.yaml, cockpit/tests/common/cockpit-clusterrolebinding_test.yaml, cockpit/tests/common/cockpit-serviceaccount_test.yaml, cockpit/tests/generator/generator-autoscaler_test.yaml, cockpit/tests/generator/generator-configmap_test.yaml, cockpit/tests/generator/generator-deployment_test.yaml, cockpit/tests/generator/generator-service_test.yaml, cockpit/tests/ui/ui-autoscaler_test.yaml, cockpit/tests/ui/ui-configmap_test.yaml, cockpit/tests/ui/ui-deployment_test.yaml, cockpit/tests/ui/ui-ingress_test.yaml, cockpit/tests/ui/ui-service_test.yaml, cockpit/values.yaml
Add Helm unit tests for the Cockpit charts
=> Add tests on Cockpit charts

apim/3.x/CHANGELOG.md, apim/3.x/Chart.yaml, apim/3.x/templates/api/api-deployment.yaml, apim/3.x/templates/gateway/gateway-deployment.yaml, apim/3.x/tests/api/deployment_test.yaml, apim/3.x/tests/gateway/deployment_test.yaml
**Issue**
https://github.com/gravitee-io/issues/issues/6895
Open service core port for management API as it was already done for the gateway.
=> APIM: Open port for core services of the management API

am/CHANGELOG.md, am/Chart.yaml, am/README.adoc, am/README.md, am/templates/gateway/gateway-configmap.yaml
fixes gravitee-io/issues#7171
**Issue**
https://github.com/gravitee-io/issues/issues/7171
Added cookie configuration to the gateway configmap.
=> fix: gateway cookie configuration

am/CHANGELOG.md, am/Chart.yaml, am/templates/api/api-configmap.yaml, am/templates/gateway/gateway-configmap.yaml, am/tests/api-configmap_test.yaml, am/tests/gateway-configmap_test.yaml
=> fix(am): allow to configure user management settings

am/templates/api/api-configmap.yaml, am/tests/api-configmap_test.yaml, am/values.yaml
**Issue**
https://github.com/gravitee-io/issues/issues/7479
Every possible configurable jetty configuration in AM is now parameterized in the AM helm chart
=> chore: jetty config AM chart

am/README.adoc, am/templates/api/api-configmap.yaml
**Issue**
https://github.com/gravitee-io/issues/issues/7479
Added documentation + fix for accesslog.path 
https://github.com/gravitee-io/helm-charts/pull/238
=> fix(am): docs + accesslog.path fix

am/CHANGELOG.md, am/Chart.yaml
=> chore(am): bump AM chart version to 1.0.41

cockpit/CHANGELOG.md, cockpit/Chart.yaml, cockpit/templates/api/api-deployment.yaml, cockpit/templates/api/api-service.yaml, cockpit/templates/generator/generator-deployment.yaml, cockpit/templates/generator/generator-service.yaml, cockpit/templates/ui/ui-service.yaml, cockpit/tests/api/api-deployment_test.yaml, cockpit/tests/api/api-service_test.yaml, cockpit/tests/generator/generator-deployment_test.yaml, cockpit/tests/generator/generator-service_test.yaml, cockpit/tests/ui/ui-deployment_test.yaml, cockpit/tests/ui/ui-service_test.yaml, cockpit/values.yaml
=> Cockpit - fix popeye warnings

ae/CHANGELOG.md, ae/Chart.yaml, ae/templates/_helpers.tpl, ae/tests/deployment_test.yaml, am/CHANGELOG.md, am/Chart.yaml, am/templates/_helpers.tpl, am/tests/api/deployment_test.yaml, am/tests/gateway/deployment_test.yaml, apim/3.x/CHANGELOG.md, apim/3.x/Chart.yaml, apim/3.x/templates/_helpers.tpl, apim/3.x/tests/api/deployment_test.yaml, apim/3.x/tests/gateway/deployment_test.yaml, cockpit/CHANGELOG.md, cockpit/Chart.yaml, cockpit/templates/_helpers.tpl, cockpit/tests/api/api-deployment_test.yaml, cockpit/tests/generator/generator-deployment_test.yaml
**Issue**
https://github.com/gravitee-io/issues/issues/XXXXX
=> feat: Add support for managed ServiceAccounts name provided by user

apim/3.x/templates/api/api-configmap.yaml, apim/3.x/tests/api/configmap_test.yaml
**Issue**
https://github.com/gravitee-io/issues/issues/7781
Add support for APIM console Pendo analytics with helm charts
=> feat(console): Add support for APIM console Pendo analytics with helm charts

apim/3.x/CHANGELOG.md, apim/3.x/Chart.yaml, apim/3.x/templates/api/api-bridge-ingress.yaml, apim/3.x/templates/api/api-configmap.yaml, apim/3.x/templates/api/api-deployment.yaml, apim/3.x/templates/api/api-service.yaml, apim/3.x/tests/api/api-bridge-ingress_test.yaml, apim/3.x/tests/api/service_bridge_test.yaml, apim/3.x/values.yaml
**Issue**
https://github.com/gravitee-io/issues/issues/XXXXX
=> feat(apim): Add support for using APIM Management API as a bridge

apim/3.x/CHANGELOG.md, apim/3.x/Chart.yaml, apim/3.x/templates/api/api-configmap.yaml, apim/3.x/tests/api/configmap_services_test.yaml, apim/3.x/values.yaml
**Issue**
https://github.com/gravitee-io/issues/issues/8271
Handle subscription service configuration
=> APIM: Handle subscription service configuration

cockpit/CHANGELOG.md, cockpit/Chart.yaml, cockpit/templates/api/api-configmap.yaml, cockpit/tests/api/api-configmap_logback_yaml_test.yaml
**Issue**
https://github.com/gravitee-io/gravitee-cockpit/issues/2940
Add logback configuration to enable one json message per line logging
=> fix(cockpit): add config to log one json message per line

am/CHANGELOG.md, am/Chart.yaml, am/templates/api/api-configmap.yaml, am/templates/gateway/gateway-configmap.yaml, am/tests/api-configmap_test.yaml, am/tests/gateway-configmap_test.yaml, am/values.yaml
related-to gravitee-io/issues#5856
=> feat(am): add template to enable SSl connections with Backends

apim/3.x/CHANGELOG.md, apim/3.x/Chart.yaml, apim/3.x/templates/api/api-configmap.yaml, apim/3.x/templates/gateway/gateway-configmap.yaml, apim/3.x/tests/api/configmap_logback_yaml_test.yaml, apim/3.x/tests/gateway/configmap_logback_yaml_test.yaml, apim/3.x/values.yaml
Enable JSON logging support
By default it is disabled
=> feat(apim): add JSON logging support

apim/3.x/CHANGELOG.md, apim/3.x/Chart.yaml, apim/3.x/templates/api/api-configmap.yaml, apim/3.x/tests/api/configmap_email_test.yaml, apim/3.x/values.yaml
**Issue**
https://graviteesource.zendesk.com/agent/tickets/4792 
Fix missing config to configure email into gravitee.yml
=> [APIM] Fix missing config to configure email into gravitee.yml

am/CHANGELOG.md, am/Chart.yaml, am/templates/common/role.yaml, am/templates/common/rolebinding.yaml, am/tests/common/role_test.yaml, am/tests/common/rolebinding_test.yaml, am/values.yaml, apim/3.x/CHANGELOG.md, apim/3.x/Chart.yaml, apim/3.x/templates/common/role.yaml, apim/3.x/templates/common/rolebinding.yaml, apim/3.x/tests/common/role_test.yaml, apim/3.x/tests/common/rolebinding_test.yaml, apim/3.x/values.yaml, cockpit/CHANGELOG.md, cockpit/Chart.yaml, cockpit/templates/common/cockpit-role.yaml, cockpit/templates/common/cockpit-rolebinding.yaml, cockpit/tests/common/cockpit-role_test.yaml, cockpit/tests/common/cockpit-rolebinding_test.yaml, cockpit/values.yaml
This PR is to solve this issues https://community.gravitee.io/t/unable-to-install-am-helm-chart-in-more-than-one-namespace-in-the-same-cluster/1248/1
=> fix: Replace ClusterRole with Role

am/CHANGELOG.md, am/Chart.yaml, am/README.adoc, am/README.md, am/templates/api/api-configmap.yaml, am/templates/gateway/gateway-configmap.yaml, am/values.yaml
=> AM-208 Manage JSON log format

am/CHANGELOG.md, am/Chart.yaml, am/README.adoc, am/README.md, am/templates/api/api-configmap.yaml, am/templates/api/api-deployment.yaml, am/templates/common/role.yaml, am/templates/common/rolebinding.yaml, am/templates/gateway/gateway-configmap.yaml, am/templates/gateway/gateway-deployment.yaml, am/tests/common/role_test.yaml, am/tests/common/rolebinding_test.yaml, am/tests/gateway-configmap_test.yaml, am/values.yaml, apim/3.x/CHANGELOG.md, apim/3.x/Chart.yaml, apim/3.x/templates/common/role.yaml, apim/3.x/templates/common/rolebinding.yaml, apim/3.x/tests/common/role_test.yaml, apim/3.x/tests/common/rolebinding_test.yaml, apim/3.x/values.yaml, cockpit/CHANGELOG.md, cockpit/Chart.yaml, cockpit/templates/common/cockpit-role.yaml, cockpit/templates/common/cockpit-rolebinding.yaml, cockpit/tests/common/cockpit-role_test.yaml, cockpit/tests/common/cockpit-rolebinding_test.yaml, cockpit/values.yaml
**Issue**
- [AM] Allow definition of AM 3.20.0 features
- Replace ClusterRole with Role
- [AM] Manage JSON log format
- [AM] add services core (a.k.a technical API) support in deployment
=> add core services to access management

am/CHANGELOG.md, am/Chart.yaml, am/templates/api/api-upgrader-job.yaml, am/tests/api/api_upgrader_test.yaml, apim/3.x/CHANGELOG.md, apim/3.x/Chart.yaml, apim/3.x/templates/api/api-upgrader-job.yaml, apim/3.x/tests/api/api_upgrader_test.yaml, cockpit/CHANGELOG.md, cockpit/Chart.yaml, cockpit/templates/api/api-upgrader-job.yaml, cockpit/tests/api/api_upgrader_test.yaml
**Issue**
https://graviteedevops.atlassian.net/browse/ARCH-71
=> Upgrader Framework - Helm pre-upgrade hook

apim/3.x/CHANGELOG.md, apim/3.x/Chart.yaml, apim/3.x/README.adoc, apim/3.x/templates/api/api-configmap.yaml, apim/3.x/templates/gateway/gateway-configmap.yaml, apim/3.x/tests/api/configmap_alert_test.yaml, apim/3.x/tests/gateway/configmap_alert_test.yaml
**Issue**
https://github.com/gravitee-io/issues/issues/8733
This PR brings additional configuration from the alert engine connector
=> chore(apim): complete alert engine configuration

am/CHANGELOG.md, am/Chart.yaml, am/README.adoc, am/README.md, am/templates/api/api-configmap.yaml, am/templates/gateway/gateway-configmap.yaml, am/tests/api-configmap_test.yaml, am/tests/gateway-configmap_test.yaml, am/values.yaml
**Issue**
https://github.com/gravitee-io/issues/issues/8733
https://github.com/gravitee-io/issues/issues/7552
https://github.com/gravitee-io/issues/issues/7555
https://github.com/gravitee-io/issues/issues/7556
Enables user activity in am helm charts
https://github.com/gravitee-io/gravitee-access-management/pull/1882
=> feat(am): support alert engine configuration + user activity in helm charts for adaptive access

ae/Chart.yaml, ae/templates/engine-configmap.yaml, ae/tests/configmap_test.yaml, ae/tests/deployment_test.yaml, ae/values.yaml
**Issue**
https://graviteedevops.atlassian.net/jira/software/c/projects/AE/boards/22
This PR brings new configuration elements to Alert Engine
=> feat(ae): add configuration related to Alert Engine 2.0.0

am/CHANGELOG.md, am/Chart.yaml, am/README.adoc, am/README.md, am/templates/api/api-configmap.yaml, am/templates/gateway/gateway-configmap.yaml, am/values.yaml
=> fix(am): manage alert triggers and settings [AM-231]

am/CHANGELOG.md, am/Chart.yaml, am/README.adoc, am/README.md, am/templates/api/api-configmap.yaml, am/templates/gateway/gateway-configmap.yaml, am/tests/api-configmap_test.yaml, am/tests/gateway-configmap_test.yaml, apim/3.x/CHANGELOG.md, apim/3.x/Chart.yaml, apim/3.x/README.adoc, apim/3.x/templates/api/api-configmap.yaml, apim/3.x/templates/gateway/gateway-configmap.yaml, apim/3.x/tests/api/configmap_alert_test.yaml, apim/3.x/tests/gateway/configmap_alert_test.yaml
**Issue**
https://gravitee.atlassian.net/browse/AE-46
This PR includes Multi DC Alert Engine connection
Related PR https://github.com/gravitee-io/gravitee-ae-connectors/pull/16
=> feat: ae connector multi dc for APIM and AM

apim/3.x/README.adoc, apim/3.x/README.md
**Issue**
https://gravitee.atlassian.net/browse/DOC-337
Added a small section describing how to use external configuration files.
=> Adding information on external configuration files.

apim/3.x/CHANGELOG.md, apim/3.x/Chart.yaml, apim/3.x/tests/api/deployment_test.yaml, apim/3.x/values.yaml
**Issue**
https://github.com/gravitee-io/issues/issues/2809
Remove `/gateway` from the gateway ingress path
=> Remove `/gateway` from the gateway ingress path

apim/3.x/CHANGELOG.md, apim/3.x/Chart.yaml, apim/3.x/values.yaml
**Issue**
https://github.com/gravitee-io/issues/issues/8094
=> fix(apim): update default ingress path for ui

apim/3.x/CHANGELOG.md, apim/3.x/Chart.yaml, apim/3.x/templates/api/api-configmap.yaml, apim/3.x/templates/gateway/gateway-configmap.yaml, apim/3.x/tests/api/configmap_api_properties_test.yaml, apim/3.x/tests/gateway/configmap_api_properties_test.yaml
**Issue**
https://github.com/gravitee-io/issues/issues/7955
https://github.com/gravitee-io/issues/issues/8730
Add API properties config of the Management API and Gateway
=> Add API properties config of the Management API and Gateway

am/CHANGELOG.md, am/Chart.yaml, apim/3.x/CHANGELOG.md, apim/3.x/Chart.yaml
**Issue**
https://github.com/gravitee-io/issues/issues/8633
https://gravitee.atlassian.net/browse/APIM-277
Update APIM and AM versions to 3.20.1
=> Update APIM and AM versions to 3.20.1

apim/3.x/CHANGELOG.md, apim/3.x/Chart.yaml, apim/3.x/values.yaml
**Issue**
NA
Update Elasticsearch and MongoDB in APIM values
=> Update Elasticsearch and MongoDB in APIM values

apim/3.x/CHANGELOG.md, apim/3.x/Chart.yaml, apim/3.x/templates/api/api-bridge-ingress.yaml, apim/3.x/templates/api/api-ingress-management.yaml, apim/3.x/templates/api/api-ingress-portal.yaml, apim/3.x/templates/api/api-technical-ingress.yaml, apim/3.x/templates/gateway/gateway-bridge-ingress.yaml, apim/3.x/templates/gateway/gateway-ingress.yaml, apim/3.x/templates/gateway/gateway-technical-ingress.yaml, apim/3.x/templates/portal/portal-ingress.yaml, apim/3.x/templates/ui/ui-ingress.yaml, apim/3.x/tests/api/ingress_bridge_test.yaml, apim/3.x/tests/api/ingress_management_test.yaml, apim/3.x/tests/api/ingress_portal_test.yaml, apim/3.x/tests/api/ingress_technical_test.yaml, apim/3.x/tests/gateway/ingress_bridge_test.yaml, apim/3.x/tests/gateway/ingress_technical_test.yaml, apim/3.x/tests/gateway/ingress_test.yaml, apim/3.x/tests/portal/ingress_test.yaml, apim/3.x/tests/ui/ingress_test.yaml, apim/3.x/values.yaml
**Issue**
https://github.com/gravitee-io/issues/issues/8393
Add pathType variable for all ingress
=> Add pathType variable for all ingress

apim/3.x/CHANGELOG.md, apim/3.x/Chart.yaml, apim/3.x/templates/api/api-configmap.yaml, apim/3.x/tests/api/configmap_test.yaml
**Issue**
https://gravitee.atlassian.net/browse/APIM-954
Add user password policy pattern section in apim api configmap.
=> refactor: add user password policy pattern

cockpit/CHANGELOG.md, cockpit/Chart.yaml, cockpit/templates/api/api-upgrader-job.yaml, cockpit/tests/api/api_upgrader_test.yaml, cockpit/values.yaml
Make upgrader framework optional
=> feat(cockpit): Make upgrader framework optional

apim/3.x/CHANGELOG.md, apim/3.x/Chart.yaml, apim/3.x/templates/gateway/gateway-configmap.yaml, apim/3.x/values.yaml
Add `gracefulShutdown` in gateway configuration
=> feat(apim): Add `gracefulShutdown` in gateway configuration

apim/3.x/README.adoc
Fix the External configuration file documentation
=> fix(apim): fix External configuration file documentation

apim/3.x/CHANGELOG.md, apim/3.x/Chart.yaml, apim/3.x/README.adoc, apim/3.x/templates/portal/portal-configmap.yaml, apim/3.x/templates/ui/ui-configmap.yaml, apim/3.x/values.yaml
**Issue**
https://community.gravitee.io/t/helm-chart-apim3-issues/311/10
Add variables `api.ingress.management.scheme` and `api.ingress.portal.scheme` default `https`
=> 8957 http management api

apim/3.x/CHANGELOG.md, apim/3.x/Chart.yaml, apim/3.x/templates/gateway/gateway-configmap.yaml, apim/3.x/tests/gateway/configmap_ssl_test.yaml, apim/3.x/values.yaml
This PR tries to add SNI to the gateway configuration.
At the moment it is not possible to modify this value via the helm charts
=> feat: add sni to the gateway configuration

apim/3.x/CHANGELOG.md, apim/3.x/Chart.yaml, apim/3.x/templates/gateway/gateway-configmap.yaml
Revert the breaking change: 'remove old cache type configuration'
=> fix(APIM): revert 'remove old cache type configuration'

apim/3.x/CHANGELOG.md, apim/3.x/Chart.yaml, apim/3.x/templates/api/api-configmap.yaml, apim/3.x/values.yaml
**Issue**
https://gravitee.atlassian.net/browse/APIM-1366
Allow user to disable Analytics in Management API
=> feat: allow disabling analytics in Management API

apim/3.x/CHANGELOG.md, apim/3.x/Chart.yaml, apim/3.x/templates/gateway/gateway-configmap.yaml, apim/3.x/values.yaml
reverted in favour of https://github.com/gravitee-io/helm-charts/pull/379
=> Revert "feat: add labels to apim gateway configmap"

apim/3.x/CHANGELOG.md, apim/3.x/Chart.yaml, apim/3.x/values.yaml
**Issue**
https://gravitee.atlassian.net/browse/APIM-1092
Wait 3.21.0 release before merging this PR and release it.
=> feat: use mongo 6 as default version

apim/3.x/BREAKING_CHANGES.md, apim/3.x/README.md
Add breaking change documentation
- File BREAKING_CHANGES.md
- Link in README.md
=> chore: add breaking change documentation

cockpit/CHANGELOG.md, cockpit/Chart.yaml, cockpit/templates/api/api-configmap.yaml, cockpit/tests/api/api-configmap_gravitee_yaml_test.yaml, cockpit/tests/api/api-deployment_test.yaml, cockpit/values.yaml
Add onboarding configuration to remember the user to configure his cockpit.
=> feat(cockpit): add onboarding configuration

cockpit/CHANGELOG.md, cockpit/Chart.yaml, cockpit/templates/api/api-configmap.yaml, cockpit/tests/api/api-configmap_gravitee_yaml_test.yaml, cockpit/tests/api/api-deployment_test.yaml, cockpit/values.yaml
**Issue**
https://gravitee.atlassian.net/browse/COC-231
Add a new property to set time before notifying when user incomplete his onboarding
=> feat(cockpit): add onboarding incomplete configuration in cockpit

cockpit/Chart.yaml, cockpit/README.adoc, cockpit/templates/api/api-configmap.yaml, cockpit/tests/api/api-configmap_gravitee_yaml_test.yaml, cockpit/values.yaml
This PR add confluence API configuration in gravitee.yml file to be able to configure cockpit for trial demo purpose.
=> feat(trial): add confluence api configuration in gravitee.yml for trial demo

cockpit/CHANGELOG.md, cockpit/Chart.yaml, cockpit/templates/ui/ui-deployment.yaml, cockpit/tests/ui/ui-deployment_test.yaml
**Issue**
https://gravitee.atlassian.net/browse/COC-364
Be able to define API_URL for cockpit ui. Needed to be able to deploy on env per PR
=> feat(cockpit): UI API_URL need to be defined in values

cockpit/CHANGELOG.md, cockpit/Chart.yaml, cockpit/templates/api/api-configmap.yaml, cockpit/tests/api/api-configmap_gravitee_yaml_test.yaml
**Issue**
https://gravitee.atlassian.net/browse/COC-364
Be able to define UI and WS endpoints and authentication callbackURL
=> feat(cockpit): UI and WS endpoints and authentication callbackURL

cockpit/CHANGELOG.md, cockpit/Chart.yaml, cockpit/requirements.lock, cockpit/requirements.yaml, cockpit/values.yaml
**Issue**
https://gravitee.atlassian.net/jira/software/c/projects/CJ/boards/19?selectedIssue=CJ-1294
Update mongodb requirement version
=> chore(cockpit): upgrade mongodb requirement version

cockpit/CHANGELOG.md, cockpit/Chart.yaml, cockpit/templates/api/api-configmap.yaml, cockpit/tests/api/api-configmap_gravitee_yaml_test.yaml, cockpit/tests/api/api-configmap_hazelcast_yaml_test.yaml, cockpit/tests/api/api-deployment_test.yaml, cockpit/values.yaml
This PR removes configuration not used anymore on latest cockpit.
It is also setting the new configuration required.
=> Update cockpit helm chart to match latest cockpit version

cockpit/CHANGELOG.md, cockpit/Chart.yaml, cockpit/templates/api/api-configmap.yaml, cockpit/tests/api/api-configmap_gravitee_yaml_test.yaml, cockpit/tests/api/api-configmap_hazelcast_yaml_test.yaml, cockpit/tests/api/api-deployment_test.yaml, cockpit/values.yaml
Because changes introduced in 1.9.6 was not compatible with oldest version of cockpit, it has been decided to create a major version of the helm chart.
=> fix(): revert changes introduced by 1.9.6

cockpit/CHANGELOG.md, cockpit/Chart.yaml, cockpit/templates/api/api-configmap.yaml, cockpit/tests/api/api-configmap_gravitee_yaml_test.yaml, cockpit/tests/api/api-configmap_hazelcast_yaml_test.yaml, cockpit/tests/api/api-deployment_test.yaml, cockpit/values.yaml
Adapt helm chart to be compatible with cockpit 4.43.0
- Add new configuration for controller
- Adapt hazelcast configuration for latest cockpit
- Remove compatible-versions values
- Update appVersion requirement as this chart is only for 4.43.0 and higher
=> Align with next cockpit version

cockpit/CHANGELOG.md, cockpit/templates/api/api-deployment.yaml, cockpit/tests/api/api-deployment_test.yaml
https://gravitee.atlassian.net/browse/ARCHI-391
All in commit msg
=> fix: split hz config for cluster and cache

cockpit/Chart.yaml
=> chore: update cockpit chart release version

cockpit/CHANGELOG.md, cockpit/Chart.yaml, cockpit/templates/api/api-configmap.yaml, cockpit/tests/api/api-configmap_gravitee_yaml_test.yaml, cockpit/tests/api/api-deployment_test.yaml
This PR introduces the necessary values for spec-gen helm charts https://gravitee.atlassian.net/browse/SAT-133
=> feat: spec-gen helm

ae/CHANGELOG.md, ae/Chart.yaml, ae/templates/engine-configmap.yaml
**Issue**
https://gravitee.atlassian.net/browse/CJ-3052
=> feat(ae): upgrade to v2.2.1 & upgrade hazelcast conf

ae/CHANGELOG.md, ae/Chart.yaml
**Issue**
https://gravitee.atlassian.net/browse/CJ-3089
=> feat(ae): upgrade to 2.3.0
